/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Presentacion;

import Conceptos.Medicos;
import Conceptos.Servicio;
import Presentacion.ServiciosValidados;
import Util.XMLWriter;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Christopher
 */
public class Medico extends javax.swing.JDialog {
    
    //Atributo de la clase medico en la ventana como arraylist que va a guardar los servicios seleccionados
    private List<String> serviciosSeleccionados = new ArrayList<>();
    private List<String> servicios;

    /**
     * Creates new form Medicos2
     */
    public Medico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        llenarTabla();
        this.setLocation(400, 200);
        
    }
    
    //Este metodo nos permite llenar la tabla de los medicos
    private void llenarTabla(){
        
        try {
            // Cargar los medicos desde el archivo XML
            ArrayList<Medicos> medicos;
            File xmlFile = new File("medicos.xml");
            medicos = util.XMLHandler.CargarMedico(xmlFile.getAbsolutePath());

            // Definir los nombres de las columnas para la tabla
            Vector<String> columnNames = new Vector<>();
            columnNames.addElement("ID");
            columnNames.addElement("Nombre Medico");
            columnNames.addElement("Puesto");
            columnNames.addElement("Telefono");
            columnNames.addElement("Servicios");

            // Crear la estructura de datos para las filas con el import de vector
            Vector<Vector<String>> rowData = new Vector<>();

            // Rellenar la tabla con los datos de los medicos usando el get implementado en la clase
            for (Medicos m : medicos) {
                
                //Mediante el vector agregamos todos elementos necesarios del arraylist
                Vector<String> row = new Vector<>();
                row.addElement(m.getId_m());
                row.addElement(m.getNombre_medico());
                row.addElement(m.getPuesto()); 
                row.addElement(m.getTelefono()); 
                
                // Obtener los servicios del medico
                List<String> servicios = m.getServicios(); 
                
                String serviciosConcat = String.join(", ", servicios); // Combinar servicios en un String
                
                row.addElement(serviciosConcat); //Anadir los elementos o servicios a la columna
            
                rowData.addElement(row);
        }

        // Crear un modelo de tabla no editable
        DefaultTableModel m = new DefaultTableModel(rowData, columnNames) {
            
            @Override
            public boolean isCellEditable(int row, int column) {
                
                // Todas las celdas serán no editables
                return false;
            }
        };

            // Establecer el modelo de la tabla
            this.Tabla_Medicos.setModel(m);
       
        //Excepcion final 
        } catch (Exception e){
            e.printStackTrace();
        }
    }
    
    // Este método devuelve los servicios seleccionados
    private List<String> obtenerServiciosSeleccionados() {
        return this.serviciosSeleccionados; 
   }
    
    //Este set nos permite asignar los servicios del medico mediante la lista y lo devuelve en servicios seleccionados
    public void setServiciosSeleccionados(List<String> servicios) {
        this.serviciosSeleccionados = servicios;
    }
    
    //Metodo para obtener los servicios seleccionados
    public List<String> getServiciosSeleccionados() {
        return this.serviciosSeleccionados; // Devolver la lista de servicios seleccionados
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        E_IDM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        E_NombreMedico = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        E_Puesto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        E_Telefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BVer = new javax.swing.JButton();
        Nuevo_Medico = new javax.swing.JButton();
        Modificar_Medico = new javax.swing.JButton();
        Borrar_Medico = new javax.swing.JButton();
        Bsaliur = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Medicos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Medicos");

        jLabel2.setText("ID");

        jLabel3.setText("Nombre");

        jLabel4.setText("Puesto");

        jLabel5.setText("Telefono");

        jLabel6.setText("Servicios");

        BVer.setText("Ver Editar");
        BVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVerAbrirSer(evt);
            }
        });

        Nuevo_Medico.setText("Nuevo");
        Nuevo_Medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nuevo_MedicoActionPerformed(evt);
            }
        });

        Modificar_Medico.setText("Modificar");
        Modificar_Medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modificar_MedicoActionPerformed(evt);
            }
        });

        Borrar_Medico.setText("Borrar");
        Borrar_Medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Borrar_MedicoActionPerformed(evt);
            }
        });

        Bsaliur.setText("Salir");
        Bsaliur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsaliurActionPerformed(evt);
            }
        });

        Tabla_Medicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        Tabla_Medicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_MedicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_Medicos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(E_IDM, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(E_Puesto))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(E_NombreMedico)
                    .addComponent(E_Telefono)
                    .addComponent(BVer, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Nuevo_Medico, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Modificar_Medico, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Borrar_Medico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(431, 431, 431)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Bsaliur)
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(E_IDM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(E_NombreMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nuevo_Medico))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(E_Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(E_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Modificar_Medico))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(BVer)
                    .addComponent(Borrar_Medico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(Bsaliur)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BVerAbrirSer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVerAbrirSer
       
        //Boton para abrir los servicios que tienen los medicos
        try {
        // Crear una instancia de ServiciosValidados esto para abrir la ventana donde vamos a establecer los servicios
        ServiciosValidados mostrarServiciosV = new ServiciosValidados(this, true);
        
        // Mostrar el jdialog
        mostrarServiciosV.setVisible(true); 
    
    //Exccepcion en caso de que haya un error al abrir la ventana
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al mostrar los servicios: " + ex.getMessage(), "Error Inmininente", JOptionPane.ERROR_MESSAGE);
    }

    
    }//GEN-LAST:event_BVerAbrirSer

    private void Nuevo_MedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nuevo_MedicoActionPerformed
        
        //Boton para agregar un nuevo medico
        try {
            
            //Llamada al writer para modificar el xml
            XMLWriter generador = new XMLWriter();
            
            //Cargamos los servicios para verificar su existencia
            generador.cargarXML("servicios.xml");
            generador.CargaServicios();
            
            //Cargamos el xml de medicos para hacer los cambios
            generador.cargarXML("medicos.xml");
            
            //Establecemos los campos de texto para obtener su contenido y agregarlo al nuevo medico
            String id_m = E_IDM.getText();
            String nombre_medico = E_NombreMedico.getText();
            String telefono = E_Telefono.getText();
            String puesto = E_Puesto.getText();
        
            // Obtener los servicios seleccionados en la otra ventana de servicios validados 
            List<String> serviciosSeleccionados = obtenerServiciosSeleccionados();
            
            //Si no se selecciona nada tira un error
            if (serviciosSeleccionados.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se han seleccionado servicios. Seleccione un servicio.", "Peligro Inminente", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            //Creamos un nuevo objeto medicos
            Medicos nuevoMedico = new Medicos();
            
            //Mediante set establecemos los atributos del medico
            nuevoMedico.setId_m(id_m);
            nuevoMedico.setNombre_medico(nombre_medico);
            nuevoMedico.setTelefono(telefono);
            nuevoMedico.setPuesto(puesto);
            
            //Con el writer de escritura agregamos el objeto medico y sus servicios
            generador.agregarMedico(nuevoMedico, serviciosSeleccionados);
            generador.guardarXML("medicos.xml");
            
            //Rellenamos la tabla
            llenarTabla();
            
            // Limpiar campos después de agregar para la siguiente persona agregada
            E_IDM.setText("");
            E_NombreMedico.setText("");
            E_Telefono.setText("");
            E_Puesto.setText("");
            
            //Mensaje de que se agrego el medico correctamente
            JOptionPane.showMessageDialog(this, "Medico agregado.", "Lo lograste!", JOptionPane.INFORMATION_MESSAGE);
        
        //Mensaje de excepcion en caso de que no se agregue nada
        } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al agregar el medico: " + ex.getMessage(), "Error Inminente", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_Nuevo_MedicoActionPerformed

    private void BsaliurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsaliurActionPerformed
      //Boton de Salir de Medicos
      
      dispose();
      
    }//GEN-LAST:event_BsaliurActionPerformed

    private void Tabla_MedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_MedicosMouseClicked
        
    // Obtener la fila seleccionada
    int filaSeleccionada = Tabla_Medicos.getSelectedRow();
    
    if (filaSeleccionada != -1) {

        // Llenar los campos de texto con los datos de la fila seleccionada
        E_IDM.setText(Tabla_Medicos.getValueAt(filaSeleccionada, 0).toString());
        E_NombreMedico.setText(Tabla_Medicos.getValueAt(filaSeleccionada, 1).toString());
        E_Puesto.setText(Tabla_Medicos.getValueAt(filaSeleccionada, 2).toString());
        E_Telefono.setText(Tabla_Medicos.getValueAt(filaSeleccionada, 3).toString());
    }
    
    }//GEN-LAST:event_Tabla_MedicosMouseClicked

    private void Borrar_MedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Borrar_MedicoActionPerformed
    
    //Boton para eliminar el medico segun el ID
    try {
        // Obtener solo el ID del médico 
        String id_m = E_IDM.getText();

        // Llamamos al writer
        XMLWriter generador = new XMLWriter();
        
        // Cargar el XML existente
        generador.cargarXML("medicos.xml");
        
        // Crear un nuevo objeto Medicos solo con el ID
        Medicos medico1 = new Medicos("", "", "", id_m, "", "", 0); // Los otros parámetros no son necesarios para la eliminación
        
        // Llamar al metodo para eliminar el médico
        generador.eliminarMedico(medico1);
        
        // Guardar los cambios en el archivo XML
        generador.guardarXML("medicos.xml");
        
        // Invocamos el metodo llenar tabla para que lo actualice
        llenarTabla();
        
        // Limpiar campos despues de borrar
        E_IDM.setText("");
        E_NombreMedico.setText("");
        E_Telefono.setText("");
        E_Puesto.setText("");

        JOptionPane.showMessageDialog(this, "Medico eliminado.", "Exitos", JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al eliminar el medico: " + e.getMessage(), "Error Inminente", JOptionPane.ERROR_MESSAGE);
    }
    
    }//GEN-LAST:event_Borrar_MedicoActionPerformed

    private void Modificar_MedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modificar_MedicoActionPerformed
       
        //Metodo de modificar el medico
        try {
            // Llamada al writer para modificar el XML
            XMLWriter generador = new XMLWriter();
        
            //Cargamos los servicios para verificar su existencia
            generador.cargarXML("servicios.xml");
            generador.CargaServicios();
        
            // Cargamos el XML de médicos para hacer los cambios
            generador.cargarXML("medicos.xml");

            // Establecemos los campos de texto para obtener su contenido
            String id_m = E_IDM.getText(); // ID del médico a modificar
            String nombre_medico = E_NombreMedico.getText();
            String telefono = E_Telefono.getText();
            String puesto = E_Puesto.getText();
        
            // Obtener los servicios seleccionados
            List<String> serviciosSeleccionados = obtenerServiciosSeleccionados();

            // Comprobar que se hayan seleccionado servicios
            if (serviciosSeleccionados.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se han seleccionado servicios. Seleccione un servicio.", "Peligro Inminente", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Crear un objeto medicos con los datos obtenidos
            Medicos medicoModificado = new Medicos();
            medicoModificado.setId_m(id_m);
            medicoModificado.setNombre_medico(nombre_medico);
            medicoModificado.setTelefono(telefono);
            medicoModificado.setPuesto(puesto);
            medicoModificado.setServicios(serviciosSeleccionados); // Esto debería funcionar ahora

            // Llamar al metodo para modificar el médico en el XML
            generador.modificarMedico(medicoModificado);

            // Guardar cambios en el XML
            generador.guardarXML("medicos.xml");

            // Rellenamos la tabla después de modificar
            llenarTabla();

            // Mensaje de exito
            JOptionPane.showMessageDialog(this, "Medico modificado exitosamente.", "Exitos", JOptionPane.INFORMATION_MESSAGE);
        
        //Excepcion Final 
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al modificar el médico: " + ex.getMessage(), "Error Inminente", JOptionPane.ERROR_MESSAGE);
        }
   
    }//GEN-LAST:event_Modificar_MedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Medico dialog = new Medico(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BVer;
    private javax.swing.JButton Borrar_Medico;
    private javax.swing.JButton Bsaliur;
    private javax.swing.JTextField E_IDM;
    private javax.swing.JTextField E_NombreMedico;
    private javax.swing.JTextField E_Puesto;
    private javax.swing.JTextField E_Telefono;
    private javax.swing.JButton Modificar_Medico;
    private javax.swing.JButton Nuevo_Medico;
    private javax.swing.JTable Tabla_Medicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
