/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Presentacion;
import Conceptos.Paciente;
import Util.XMLWriter;
import java.io.File;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Christopher
 */
public class Pacientes extends javax.swing.JDialog {

    /**
     * Creates new form Pacientes1
     */
    public Pacientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        llenarTabla();
        this.setLocation(400, 200);
        
        
    }
    
    private void llenarTabla(){
        try {
            // Cargar los pacientes desde el archivo XML
            ArrayList<Paciente> pacientes;
            File xmlFile = new File("Data/pacientes.xml");
            pacientes = Util.XMLHandler.CargarPacientes(xmlFile.getAbsolutePath());

            // Definir los nombres de las columnas para la tabla
            Vector<String> columnNames = new Vector<>();
            columnNames.addElement("ID");
            columnNames.addElement("Nombre");
            columnNames.addElement("Telefono");
            columnNames.addElement("Email"); // Asegúrate de que coincida con el valor que quieres mostrar

            // Crear la estructura de datos para las filas
            Vector<Vector<String>> rowData = new Vector<>();

            // Rellenar la tabla con los datos de los pacientes
            for (Paciente p : pacientes) {
                
                Vector<String> row = new Vector<>();
                row.addElement(p.getId());
                row.addElement(p.getNombre());
                row.addElement(p.getTelefono());
                row.addElement(p.getEmail());
                rowData.addElement(row);
        }

        // Crear un modelo de tabla no editable
        DefaultTableModel m = new DefaultTableModel(rowData, columnNames) {
            
            @Override
            public boolean isCellEditable(int row, int column) {
                // Todas las celdas serán no editables
                return false;
            }
        };

            // Establecer el modelo de la tabla
            this.Tabla_Pacientes.setModel(m);
       
        } catch (Exception e){
            e.printStackTrace();
        }
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Labelemail = new java.awt.Label();
        Bsalir = new javax.swing.JButton();
        label2 = new java.awt.Label();
        BNuevo = new javax.swing.JButton();
        BModificar = new javax.swing.JButton();
        Bborrar = new javax.swing.JButton();
        Bsalir2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        label1 = new java.awt.Label();
        E_Nombre = new java.awt.TextField();
        Lnombre = new java.awt.Label();
        E_Email = new java.awt.TextField();
        Ltelefono = new java.awt.Label();
        E_Telefono = new java.awt.TextField();
        Labelemail1 = new java.awt.Label();
        E_ID = new java.awt.TextField();
        Nuevo_Paciente = new javax.swing.JButton();
        Modificar_Paciente = new javax.swing.JButton();
        Borrar_Paciente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla_Pacientes = new javax.swing.JTable();
        Boton_Salir_Pacientes = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Labelemail.setName("Email"); // NOI18N
        Labelemail.setText("Email");

        Bsalir.setText("Salir");
        Bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsalirActionPerformed(evt);
            }
        });

        label2.setText("Pacientes");

        BNuevo.setText("Nuevo");

        BModificar.setText("Modificar");

        Bborrar.setText("Borrar");
        Bborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BborrarActionPerformed(evt);
            }
        });

        Bsalir2.setText("Salir");
        Bsalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bsalir2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(235, 250, 255));

        label3.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        label3.setText("Pacientes");

        label1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        label1.setName("ID"); // NOI18N
        label1.setText("ID");

        E_Nombre.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N

        Lnombre.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        Lnombre.setText("Nombre");

        E_Email.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        E_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_EmailActionPerformed(evt);
            }
        });

        Ltelefono.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        Ltelefono.setText("Telefono");

        E_Telefono.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        E_Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_TelefonoActionPerformed(evt);
            }
        });

        Labelemail1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        Labelemail1.setName("Email"); // NOI18N
        Labelemail1.setText("Email");

        E_ID.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        E_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_IDActionPerformed(evt);
            }
        });

        Nuevo_Paciente.setBackground(new java.awt.Color(153, 215, 235));
        Nuevo_Paciente.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        Nuevo_Paciente.setText("Nuevo");
        Nuevo_Paciente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        Nuevo_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nuevo_PacienteActionPerformed(evt);
            }
        });

        Modificar_Paciente.setBackground(new java.awt.Color(153, 215, 235));
        Modificar_Paciente.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        Modificar_Paciente.setText("Modificar");
        Modificar_Paciente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        Modificar_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modificar_PacienteActionPerformed(evt);
            }
        });

        Borrar_Paciente.setBackground(new java.awt.Color(153, 215, 235));
        Borrar_Paciente.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        Borrar_Paciente.setText("Borrar");
        Borrar_Paciente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        Borrar_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Borrar_PacienteActionPerformed(evt);
            }
        });

        Tabla_Pacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Telefono", "Email"
            }
        ));
        Tabla_Pacientes.setToolTipText("");
        Tabla_Pacientes.setCellSelectionEnabled(true);
        Tabla_Pacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_PacientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabla_Pacientes);
        Tabla_Pacientes.getAccessibleContext().setAccessibleName("");

        Boton_Salir_Pacientes.setBackground(new java.awt.Color(153, 215, 235));
        Boton_Salir_Pacientes.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        Boton_Salir_Pacientes.setText("Salir");
        Boton_Salir_Pacientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        Boton_Salir_Pacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Salir_PacientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(Ltelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(E_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(E_Telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(Lnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(Labelemail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(E_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Modificar_Paciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Borrar_Paciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nuevo_Paciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE))
                .addGap(159, 159, 159))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Boton_Salir_Pacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(Nuevo_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(E_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Lnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(E_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Labelemail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ltelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Modificar_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(Borrar_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(Boton_Salir_Pacientes)
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsalirActionPerformed
        
    }//GEN-LAST:event_BsalirActionPerformed

    private void BborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BborrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BborrarActionPerformed

    private void Bsalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bsalir2ActionPerformed
        
    }//GEN-LAST:event_Bsalir2ActionPerformed

    private void Boton_Salir_PacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Salir_PacientesActionPerformed
        
    //Boton que sale de la ventana de tipo dialog clientes pero no cierra el programa
        
        dispose();

    }//GEN-LAST:event_Boton_Salir_PacientesActionPerformed

    private void Tabla_PacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_PacientesMouseClicked
    
    // Obtener la fila seleccionada
    int filaSeleccionada = Tabla_Pacientes.getSelectedRow();
    
    if (filaSeleccionada != -1) {

        // Llenar los campos de texto con los datos de la fila seleccionada
        E_ID.setText(Tabla_Pacientes.getValueAt(filaSeleccionada, 0).toString());
        E_Nombre.setText(Tabla_Pacientes.getValueAt(filaSeleccionada, 1).toString());
        E_Telefono.setText(Tabla_Pacientes.getValueAt(filaSeleccionada, 2).toString());
        E_Email.setText(Tabla_Pacientes.getValueAt(filaSeleccionada, 3).toString());
    }

    }//GEN-LAST:event_Tabla_PacientesMouseClicked

    private void Borrar_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Borrar_PacienteActionPerformed

        try {
            // Obtener los datos de los campos de texto
            String id = E_ID.getText();
            String nombre = E_Nombre.getText();
            String telefono = E_Telefono.getText();
            String email = E_Email.getText();
            
            // Si alguno de los campos esta vacio
            if (id.isEmpty() || nombre.isEmpty() || telefono.isEmpty() || email.isEmpty() ) {
                JOptionPane.showMessageDialog(this, "No has seleccionado ningun paciente para borrar. Selecciona un paciente.", "Peligro Inminente", JOptionPane.WARNING_MESSAGE);
                return;
            }

            //Llamamos al writer
            XMLWriter generador = new XMLWriter();

            // Cargar el XML existente
            generador.cargarXML("Data/pacientes.xml");

            // Crear un nuevo objeto Paciente
            Paciente paciente1 = new Paciente(id, nombre, telefono, email);

            // Agregar pacientes usando el objeto
            generador.eliminarPaciente(paciente1);

            // Guardar los cambios
            generador.guardarXML("Data/pacientes.xml");

            //Invocamos el metodo llenar tabla para que lo actualice
            llenarTabla();

            // Limpiar campos después de agregar para la siguiente persona agregada
            E_ID.setText("");
            E_Nombre.setText("");
            E_Telefono.setText("");
            E_Email.setText("");

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_Borrar_PacienteActionPerformed

    private void Modificar_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modificar_PacienteActionPerformed

        //Boton para modificar los pacientes ya existentes
        try {
            // Obtener los datos de los textfields
            String id = E_ID.getText();
            String nombre = E_Nombre.getText();
            String telefono = E_Telefono.getText();
            String email = E_Email.getText();
            
            // Si alguno de los campos esta vacio
            if (id.isEmpty() || nombre.isEmpty() || telefono.isEmpty() || email.isEmpty() ) {
                JOptionPane.showMessageDialog(this, "No has seleccionado ningun paciente para modificar. Selecciona un paciente.", "Peligro Inminente", JOptionPane.WARNING_MESSAGE);
                return;
            }

            //Llamamos al writer
            XMLWriter generador = new XMLWriter();

            // Cargar el XML existente
            generador.cargarXML("Data/pacientes.xml");

            // Crear un nuevo objeto Paciente
            Paciente paciente1 = new Paciente(id, nombre, telefono, email);

            // Agregar pacientes usando el objeto, implementamos el metodo modificar paciente para cambiar los datos en el objeto
            generador.modificarPaciente(paciente1);

            // Guardar los cambios
            generador.guardarXML("Data/pacientes.xml");

            //Invocamos el metodo llenar tabla para que lo actualice
            llenarTabla();

            // Limpiar campos después de agregar para la siguiente persona agregada
            E_ID.setText("");
            E_Nombre.setText("");
            E_Telefono.setText("");
            E_Email.setText("");

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_Modificar_PacienteActionPerformed

    private void Nuevo_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nuevo_PacienteActionPerformed

        try {
            // Obtener los datos de los textfields
            String id = E_ID.getText();
            String nombre = E_Nombre.getText();
            String telefono = E_Telefono.getText();
            String email = E_Email.getText();
            
            // Si alguno de los campos esta vacio
            if (id.isEmpty() || nombre.isEmpty() || telefono.isEmpty() || email.isEmpty() ) {
                JOptionPane.showMessageDialog(this, "No has agregado nada en los campos de texto para agregar un paciente. Digita en los campos de texto.", "Peligro Inminente", JOptionPane.WARNING_MESSAGE);
                return;
            }

            //Llamamos al writer
            XMLWriter generador = new XMLWriter();

            // Cargar el XML existente
            generador.cargarXML("Data/pacientes.xml");

            // Crear un nuevo objeto Paciente
            Paciente paciente1 = new Paciente(id, nombre, telefono, email);

            // Agregar pacientes usando el objeto al metodo del parser de escritura
            generador.agregarPaciente(paciente1);

            // Guardar los cambios
            generador.guardarXML("Data/pacientes.xml");

            //Invocamos el metodo llenar tabla para que lo actualice
            llenarTabla();

            // Limpiar campos después de agregar para la siguiente persona agregada
            E_ID.setText("");
            E_Nombre.setText("");
            E_Telefono.setText("");
            E_Email.setText("");

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_Nuevo_PacienteActionPerformed

    private void E_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E_EmailActionPerformed

    private void E_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E_IDActionPerformed

    private void E_TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E_TelefonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pacientes dialog = new Pacientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BModificar;
    private javax.swing.JButton BNuevo;
    private javax.swing.JButton Bborrar;
    private javax.swing.JButton Borrar_Paciente;
    private javax.swing.JButton Boton_Salir_Pacientes;
    private javax.swing.JButton Bsalir;
    private javax.swing.JButton Bsalir2;
    private java.awt.TextField E_Email;
    private java.awt.TextField E_ID;
    private java.awt.TextField E_Nombre;
    private java.awt.TextField E_Telefono;
    private java.awt.Label Labelemail;
    private java.awt.Label Labelemail1;
    private java.awt.Label Lnombre;
    private java.awt.Label Ltelefono;
    private javax.swing.JButton Modificar_Paciente;
    private javax.swing.JButton Nuevo_Paciente;
    private javax.swing.JTable Tabla_Pacientes;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    // End of variables declaration//GEN-END:variables
}
