/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Conceptos.Medicos;
import Presentacion.Pacientes;
import Presentacion.Servicios;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author INTEL
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
                setTitle("Principal");

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        MClientes = new javax.swing.JMenuItem();
        MServicio = new javax.swing.JMenuItem();
        Mmedicos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setText("label1");

        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(0, 153, 153));
        jMenu2.setText("Util");

        MClientes.setText("Clientes");
        MClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MClientesActionPerformed(evt);
            }
        });
        jMenu2.add(MClientes);

        MServicio.setText("Servicios");
        MServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MServicioActionPerformed(evt);
            }
        });
        jMenu2.add(MServicio);

        Mmedicos.setText("Medicos");
        Mmedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MmedicosActionPerformed(evt);
            }
        });
        jMenu2.add(Mmedicos);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MClientesActionPerformed
      SwingUtilities.invokeLater(new Runnable() {
        @Override
        public void run() {
            // Instancia de la clase Pacientes, que debe extender JFrame
            Pacientes ventanaPacientes = new Pacientes();
            ventanaPacientes.setSize(800, 500);
            ventanaPacientes.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            // Centrar la ventana en la pantalla
            ventanaPacientes.setLocationRelativeTo(null);
            // Mostrar la ventana
            ventanaPacientes.setVisible(true);
        }
    });
    }//GEN-LAST:event_MClientesActionPerformed

    private void MServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MServicioActionPerformed
        SwingUtilities.invokeLater(new Runnable() {
        @Override
        public void run() {
            // Instancia de la clase Pacientes, que debe extender JFrame
            Servicios ventanaServicios = new Servicios();
            ventanaServicios.setSize(800, 500);
            ventanaServicios.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            // Centrar la ventana en la pantalla
            ventanaServicios.setLocationRelativeTo(null);
            // Mostrar la ventana
            ventanaServicios.setVisible(true);
        }
    });
    }//GEN-LAST:event_MServicioActionPerformed

    private void MmedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MmedicosActionPerformed
        SwingUtilities.invokeLater(new Runnable() {
        @Override
        public void run() {
            // Instancia de la clase Pacientes, que debe extender JFrame
            Medico ventanaMedico = new Medico();
            ventanaMedico.setSize(800, 500);
            ventanaMedico.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            // Centrar la ventana en la pantalla
            ventanaMedico.setLocationRelativeTo(null);
            // Mostrar la ventana
            ventanaMedico.setVisible(true);
        }
    });
    }//GEN-LAST:event_MmedicosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MClientes;
    private javax.swing.JMenuItem MServicio;
    private javax.swing.JMenuItem Mmedicos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
