/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Presentacion;

import Conceptos.Servicio;
import Util.XMLWriter;
import java.io.File;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Christopher
 */
public class Servicios extends javax.swing.JDialog {

    /**
     * Creates new form Servicios2
     */
    public Servicios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        llenarTabla();
        this.setLocation(400, 200);
    }
    
    private void llenarTabla(){
        try {
            // Cargar los servicios desde el archivo XML
            ArrayList<Servicio> servicios;
            File xmlFile = new File("Data/servicios.xml");
            servicios = Util.XMLHandler.CargarServicios(xmlFile.getAbsolutePath());

            // Definir los nombres de las columnas para la tabla
            Vector<String> columnNames = new Vector<>();
            columnNames.addElement("ID");
            columnNames.addElement("Nombre Servicio");
            columnNames.addElement("Precio");

            // Crear la estructura de datos para las filas con el import de vector
            Vector<Vector<String>> rowData = new Vector<>();

            // Rellenar la tabla con los datos de los pacientes
            for (Servicio s : servicios) {
                
                Vector<String> row = new Vector<>();
                row.addElement(s.getId());
                row.addElement(s.getNombre_servicio());
                row.addElement(String.valueOf(s.getPrecio())); //Usamos value of para pasar el precio a double a string
                rowData.addElement(row);
        }

        // Crear un modelo de tabla no editable
        DefaultTableModel m = new DefaultTableModel(rowData, columnNames) {
            
            @Override
            public boolean isCellEditable(int row, int column) {
                
                // Todas las celdas serán no editables
                return false;
            }
        };

            // Establecer el modelo de la tabla
            this.Tabla_Servicios.setModel(m);
       
        //Excepcion final 
        } catch (Exception e){
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Servicios = new javax.swing.JTable();
        LID = new java.awt.Label();
        E_ID = new java.awt.TextField();
        LNombre = new java.awt.Label();
        E_NombreServicio = new java.awt.TextField();
        LPrecio = new java.awt.Label();
        E_Precio = new java.awt.TextField();
        Boton_Nuevo = new javax.swing.JButton();
        Boton_Modificar = new javax.swing.JButton();
        Boton_Borrar = new javax.swing.JButton();
        Boton_Salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 250, 255));

        Tabla_Servicios.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        Tabla_Servicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        Tabla_Servicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_ServiciosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_Servicios);

        LID.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        LID.setText("ID");

        E_ID.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N

        LNombre.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        LNombre.setText("Nombre");

        E_NombreServicio.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N

        LPrecio.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        LPrecio.setText("Precio");

        E_Precio.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N

        Boton_Nuevo.setBackground(new java.awt.Color(153, 215, 235));
        Boton_Nuevo.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        Boton_Nuevo.setText("Nuevo");
        Boton_Nuevo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        Boton_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_NuevoActionPerformed(evt);
            }
        });

        Boton_Modificar.setBackground(new java.awt.Color(153, 215, 235));
        Boton_Modificar.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        Boton_Modificar.setText("Modificar");
        Boton_Modificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        Boton_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_ModificarActionPerformed(evt);
            }
        });

        Boton_Borrar.setBackground(new java.awt.Color(153, 215, 235));
        Boton_Borrar.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        Boton_Borrar.setText("Borrar");
        Boton_Borrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        Boton_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_BorrarActionPerformed(evt);
            }
        });

        Boton_Salir.setBackground(new java.awt.Color(153, 215, 235));
        Boton_Salir.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        Boton_Salir.setText("Salir");
        Boton_Salir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        Boton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_SalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        jLabel1.setText("Servicios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(LID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(E_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(E_Precio, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(E_NombreServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Boton_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Boton_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1)
                                .addGap(74, 74, 74)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E_NombreServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(Boton_Nuevo)
                                .addGap(18, 18, 18)
                                .addComponent(Boton_Modificar)
                                .addGap(18, 18, 18)
                                .addComponent(Boton_Borrar)))
                        .addGap(87, 87, 87)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(Boton_Salir)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_NuevoActionPerformed
        
        //Accion del boton nuevo servicio para agregar un servicio a la lista
        try {
            
            // Obtener los datos de los campos de texto
            String id = E_ID.getText();
            String nombre_servicio = E_NombreServicio.getText();
            String precioTexto = E_Precio.getText();  // Obtener precio como String

            // Si alguno de los campos esta vacio
            if (id.isEmpty() || nombre_servicio.isEmpty() || precioTexto.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No has agregado nada en los campos de texto. Digita un servicio.", "Peligro Inminente", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Verificar si el campo de precio contiene un valor numerico valido
            double precio;
            
            try {
                precio = Double.parseDouble(precioTexto);  // Convertir el texto a double
            
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El precio no es valido. Ingrese un valor numerico.", "Error Inminente", JOptionPane.ERROR_MESSAGE);
                return;
            }           
            
            //Llamamos al writer
            XMLWriter generador = new XMLWriter();
            
            // Cargar el xml existente
            generador.cargarXML("Data/servicios.xml");
            
            // Crear un nuevo objeto servicio
            Servicio servicio1 = new Servicio(id, nombre_servicio, precio);
            
            // Agregar servicios a lista de objetos y a la tabla junto con el xml, aplicando el xmlwriter
            generador.agregarServicio(servicio1);
            
            // Guardar los cambios
            generador.guardarXML("Data/servicios.xml");
            
            //Invocamos el metodo llenar tabla para que lo actualice
            llenarTabla();
            
            // Limpiar campos después de agregar para el siguiente servicio 
            E_ID.setText("");
            E_NombreServicio.setText("");
            E_Precio.setText("");
            
         
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_Boton_NuevoActionPerformed

    private void Boton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SalirActionPerformed
        //Boton para salir del JDialog
        
        dispose();
        
    }//GEN-LAST:event_Boton_SalirActionPerformed

    private void Tabla_ServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_ServiciosMouseClicked
    
    // Obtener la fila seleccionada
    int filaSeleccionada = Tabla_Servicios.getSelectedRow();
    
    if (filaSeleccionada != -1) {

        // Llenar los campos de texto con los datos de la fila seleccionada
        E_ID.setText(Tabla_Servicios.getValueAt(filaSeleccionada, 0).toString());
        E_NombreServicio.setText(Tabla_Servicios.getValueAt(filaSeleccionada, 1).toString());
        E_Precio.setText(Tabla_Servicios.getValueAt(filaSeleccionada, 2).toString());
    }
    
    }//GEN-LAST:event_Tabla_ServiciosMouseClicked

    private void Boton_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_ModificarActionPerformed
       
        //Accion del boton modificar servicio para modificar un servicio de la lista
        try {
            
            // Obtener los datos de los campos de texto
            String id = E_ID.getText();
            String nombre_servicio = E_NombreServicio.getText();
            String precioTexto = E_Precio.getText();  // Obtener precio como String

            // Si alguno de los campos esta vacio
            if (id.isEmpty() || nombre_servicio.isEmpty() || precioTexto.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se han seleccionado servicios para modificar. Seleccione un servicio.", "Peligro Inminente", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Verificar si el campo de precio contiene un valor numerico valido
            double precio;
            
            try {
                precio = Double.parseDouble(precioTexto);  // Convertir el texto a double
            
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El precio no es valido. Ingrese un valor numerico.", "Error Inminente", JOptionPane.ERROR_MESSAGE);
                return;
            }           
            
             // Llamamos al writer
            XMLWriter generador = new XMLWriter();

            // Cargar el xml existente
            generador.cargarXML("Data/servicios.xml");
            
            // Crear un nuevo objeto servicio
            Servicio servicio1 = new Servicio(id, nombre_servicio, precio);
            
            // Modificar servicios a lista de objetos y a la tabla junto con el xml, aplicando el xmlwriter
            generador.modificarServicios(servicio1);
            
            // Guardar los cambios
            generador.guardarXML("Data/servicios.xml");
            
            //Invocamos el metodo llenar tabla para que lo actualice
            llenarTabla();
            
            // Limpiar campos después de agregar para el siguiente servicio 
            E_ID.setText("");
            E_NombreServicio.setText("");
            E_Precio.setText("");
            
         
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_Boton_ModificarActionPerformed

    private void Boton_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_BorrarActionPerformed
         
        //Accion del boton eliminar servicio para eliminar un servicio de la lista
        try {
            
            // Obtener los datos de los campos de texto
            String id = E_ID.getText();
            String nombre_servicio = E_NombreServicio.getText();
            String precioTexto = E_Precio.getText();  // Obtener precio como String

            // Si alguno de los campos esta vacio
            if (id.isEmpty() || nombre_servicio.isEmpty() || precioTexto.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No has agregado nada en los campos de texto para borrar. Selecciona un servicio.", "Peligro Inminente", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Verificar si el campo de precio contiene un valor numerico valido
            double precio;
            
            try {
                precio = Double.parseDouble(precioTexto);  // Convertir el texto a double
            
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El precio no es valido. Ingrese un valor numerico.", "Error Inminente", JOptionPane.ERROR_MESSAGE);
                return;
            }          
            
            //Llamamos al writer
            XMLWriter generador = new XMLWriter();
            
            // Cargar el xml existente
            generador.cargarXML("Data/servicios.xml");
            
            // Crear un nuevo objeto servicio
            Servicio servicio1 = new Servicio(id, nombre_servicio, precio);
            
            // Eliminar servicios de lista de objetos y de la tabla junto con el xml, aplicando el xmlwriter
            generador.eliminarServicio(servicio1);
            
            // Guardar los cambios
            generador.guardarXML("Data/servicios.xml");
            
            //Invocamos el metodo llenar tabla para que lo actualice
            llenarTabla();
            
            // Limpiar campos después de agregar para el siguiente servicio 
            E_ID.setText("");
            E_NombreServicio.setText("");
            E_Precio.setText("");
            
         
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_Boton_BorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Servicios dialog = new Servicios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Borrar;
    private javax.swing.JButton Boton_Modificar;
    private javax.swing.JButton Boton_Nuevo;
    private javax.swing.JButton Boton_Salir;
    private java.awt.TextField E_ID;
    private java.awt.TextField E_NombreServicio;
    private java.awt.TextField E_Precio;
    private java.awt.Label LID;
    private java.awt.Label LNombre;
    private java.awt.Label LPrecio;
    private javax.swing.JTable Tabla_Servicios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
