/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Presentacion;

import Conceptos.Servicio;
import Conceptos.Medicos;
import Presentacion.Medico;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.Arrays;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author INTEL
 */
public class ServiciosValidados extends javax.swing.JDialog {
    
    //Atributo de los servicios seleccionados
    private List<String> serviciosSeleccionados;
    
    
    //Constructor de servicios validados 
    public ServiciosValidados(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        this.serviciosSeleccionados = new ArrayList<>();
        

        initComponents();
        llenarTablaServicios();
        this.setLocation(400, 200);
    }
    //Metodo para llenar la tabla 
    private void llenarTablaServicios() {
        
        // Definir los nombres de las columnas
        Vector<String> columnNames = new Vector<>();
        columnNames.add("Seleccionar"); // Columna para checkbox
        columnNames.add("ID");
        columnNames.add("Nombre Servicio");
        
        // Cargar los servicios desde el archivo XML
        ArrayList<Servicio> servicios;
        File xmlFile = new File("servicios.xml");
        servicios = util.XMLHandler.CargarServicios(xmlFile.getAbsolutePath());

        // Crear la estructura de datos para las filas
        Vector<Vector<Object>> rowData = new Vector<>();

        //For para recorrer y agregar todos los servicios de la clase servicio
        for (Servicio s : servicios) {
            
            Vector<Object> row = new Vector<>();
            
            row.add(false); 
            row.addElement(s.getId());
            row.addElement(s.getNombre_servicio());
            rowData.add(row);
        }

        // Crear el modelo de tabla
        DefaultTableModel model = new DefaultTableModel(rowData, columnNames) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 0) { // Primera columna es para checkbox entonces si se puede modificar
                    return Boolean.class;
                }
                return super.getColumnClass(columnIndex);
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 0; // Solo la columna del checkbox es editable
            }
        };

        // Establecer el modelo en la tabla
        Tabla_ServiciosV.setModel(model);
    }
    
    //Metodo para obtener los servicios seleccionados por el usuario
    private List<String> obtenerServiciosSeleccionados() {
        
        //Instanciamos el arraylist
        List<String> serviciosSeleccionados = new ArrayList<>();
        
        DefaultTableModel model = (DefaultTableModel) Tabla_ServiciosV.getModel();
        
        //Recorre todas las filas
        for (int i = 0; i < model.getRowCount(); i++) {
            Boolean seleccionado = (Boolean) model.getValueAt(i, 0); // Checkbox en la primera columna
                
                //Si el checkbox es diferente de null 
                if (seleccionado != null && seleccionado) {
                String servicioId = (String) model.getValueAt(i, 1); // ID del servicio en la segunda columna //Obtiene el valor 1 como si estuviera seleccionado
                
                serviciosSeleccionados.add(servicioId);//Se agrega a los servicios seleccionados de la tabla
            }
        }
        
        //Retorna dichos servicios seleccionados
        return serviciosSeleccionados;
    }

    
    //Metodo para obtener los servicios seleccionados
    public List<String> getServiciosSeleccionados() {
        return this.serviciosSeleccionados; // Devolver la lista de servicios seleccionados
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Bcancelar = new javax.swing.JButton();
        Boton_Aceptar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_ServiciosV = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Bcancelar.setText("Cancelar");
        Bcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcancelarActionPerformed(evt);
            }
        });

        Boton_Aceptar.setText("Aceptar");
        Boton_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_AceptarActionPerformed(evt);
            }
        });

        jLabel2.setText("Servicios del medico");

        Tabla_ServiciosV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Verificar", "Title 2", "Title 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla_ServiciosV);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Bcancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Boton_Aceptar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel2)))
                .addGap(0, 80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bcancelar)
                    .addComponent(Boton_Aceptar))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_AceptarActionPerformed
    
     //Boton para aceptar los servicios agregados al medico

    try {

        //Mediante una lista de seleccionados usamos el metodo de obtener sevicios de la tabla
        List<String> seleccionados = obtenerServiciosSeleccionados();

        //Si no hay ningun seleccionado se devuelve un mensaje
        if (seleccionados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se han seleccionado servicios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //Establecemos esto como atributo para usarlo posteriormente en el agregar
        this.serviciosSeleccionados = seleccionados;

        // Pasar los servicios seleccionados a la clase de medicos con un metodo set
        ((Medico)getParent()).setServiciosSeleccionados(this.serviciosSeleccionados);

        //Mensaje que menciona que los servicios se agregaron correctamente
        JOptionPane.showMessageDialog(this, "Servicios asignados exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();

    //Mensaje de error en caso de que no se procesen los servicios
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al procesar los servicios: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    
      
    }//GEN-LAST:event_Boton_AceptarActionPerformed

    private void BcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BcancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiciosValidados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiciosValidados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiciosValidados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiciosValidados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        java.util.logging.Logger.getLogger(ServiciosValidados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcancelar;
    private javax.swing.JButton Boton_Aceptar;
    private javax.swing.JTable Tabla_ServiciosV;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
